# Generated by Django 5.1.1 on 2024-10-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
